### PR TITLE
Add support for lunar eclipses

### PR DESCRIPTION
**Pull request by porst17**
So far, only the Moon would cast shadows onto the Earth. Now, the Earth also casts shadows onto the Moon.

### CODE REVIEW

**Comment by danielramosg** [comment]
This Pull Request does not fix the lunar eclipses. However, the two parameters to change are in lines 1071 and 1075. I do not have edit rights to this repo, you can change that.

To test, just run the app in the default settings. Initially, the Moon is in a position casting shadow on the Earth, which is stationary (speed=0). A few seconds later, the Moon has completed half its orbit around the Earth, and the Earth should be casting shadow on the Moon.

There is a lot of dead code in this app. The functions `updateEarth` and `updateMoon` (that you changed) are only called from a menu that is disabled (the `circleVarious` div, which is hidden).

**Comment by porst17** [comment]
@danielramosg You should have write access now. Please push your fixes to this branch. I am not able to test this any further due to current workload caused by other projects. Thanks.

**Comment by danielramosg** [comment]
@DoroteaDudas, in case you happen to see this, is there any reason why lunar eclipses were disabled from the app? 

I would like to use this app for a workshop for the International Day of Mathematics, March 14th, 2025, which coincides with a lunar eclipse.

**Comment by porst17** [comment]
These changes are now in `master` and `devel`, but I needed to force-push `devel` because it was messed up by a previous commit. Therefore, there is no need to merge this PR and I'll just close it.

**Pull request closed without merging**
